/**
 * Writes supabase/seed.sql from the committed 2026 snapshot, so a fresh
 * Supabase project gets the same real league the SQLite app ships with.
 *
 *   npx tsx scripts/supabase-seed.ts
 *
 * The snapshot goes in through the raw layer like any live fetch would, so
 * even seeded rows trace back to a payload.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { TEAM_BRAND } from "../supabase/team-brand";

const root = process.cwd();
const seed = JSON.parse(readFileSync(join(root, "data/seed/currie-cup-2026.json"), "utf8"));

const q = (v: unknown) =>
  v === null || v === undefined ? "null" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`;

const out: string[] = [
  "-- Generated by scripts/supabase-seed.ts from data/seed/currie-cup-2026.json. Do not edit.",
  "begin;",
  "insert into public.competitions (id, name, short_name) values ('5069', 'Currie Cup Premier Division', 'Currie Cup') on conflict (id) do nothing;",
  `insert into public.seasons (id, name, is_replay, competition_id, feed_season, starts_on) values (${q(seed.season)}, ${q(`${seed.competition} ${seed.season}`)}, true, '5069', ${q(seed.season)}, '2026-07-17')`,
  "  on conflict (id) do update set name = excluded.name, is_replay = excluded.is_replay;",
  "",
  `insert into raw.feed_payloads (source, endpoint, params, payload) values ('seed', 'data/seed/currie-cup-2026.json', '{}',`,
  `  ${q(JSON.stringify(seed))}::jsonb) on conflict do nothing;`,
  "",
];

for (const t of seed.teams) {
  const b = TEAM_BRAND[t.id];
  out.push(
    `insert into public.teams (id, name, display_name, short_name, stadium, colour, colour_ink, badge_url, source) values (` +
      [t.id, t.name, t.display_name, t.short_name, t.stadium, b?.primary, b?.ink, b?.badge, t.source].map(q).join(", ") +
      `) on conflict (id) do update set display_name = excluded.display_name, short_name = excluded.short_name,` +
      ` stadium = excluded.stadium, colour = excluded.colour, colour_ink = excluded.colour_ink, badge_url = excluded.badge_url;`,
  );
}
out.push("");

for (const m of seed.matches) {
  out.push(
    `insert into public.matches (id, season, round, kickoff_at, home_team_id, away_team_id, home_score, away_score, venue, status, source, raw_id) values (` +
      [m.id, m.season, m.round, m.kickoff_utc, m.home_team_id, m.away_team_id, m.home_score, m.away_score, m.venue, m.status, "seed"].map(q).join(", ") +
      `, (select max(id) from raw.feed_payloads where source = 'seed')) on conflict (id) do nothing;`,
  );
}
out.push("");

const bp = seed.published_final_bonus_points;
if (bp) {
  for (const [team, pts] of Object.entries(bp.points as Record<string, number>)) {
    out.push(
      `insert into public.season_bonus_points (season, team_id, bonus_points, source, as_of) values (` +
        [seed.season, team, pts, bp.source, bp.as_of].map(q).join(", ") + `) on conflict do nothing;`,
    );
  }
}
out.push("commit;", "");

writeFileSync(join(root, "supabase/seed.sql"), out.join("\n"));
console.log(`Wrote supabase/seed.sql: ${seed.teams.length} teams, ${seed.matches.length} matches.`);
